# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18b6c3f3c43d460175015c3bfa795c3a71e4b021e9b6d6a4526a0875d585c4a9ced3de314557c78a239ee89d7eba0c5fe416ef9fcdbcd9e284fd38556b62251a

test:
  secret_key_base: f3c501f986303a7b0385dcd52251dc52d4018c34ab6dd2dca25fae661bc32de8014830fe6e9ac712d71258c5b5e47e9d72f0145e522db8c8b870f11ce85e3f77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
